### ISSUE TITLE
Tour de algorithm Roadmap 0.1v

### ISSUE THREAD

**Issue by malkoG** [kodingwarrior/kodingwarrior.github.io#36]
* [ ] (Tour de algorithm) Introduction

## 알고리즘 분야별 Todo List
* [ ] (Tour de algorithm) Brute-forcing / Backtracking
* [ ] (Tour de algorithm) Essential Data structure - Stack/Queue/Tree
* [ ] (Tour de algorithm) Dynamic Programming
* [ ] (Tour de algorithm) Graph Traversal - DFS/BFS
* [ ] (Tour de algorithm) Shortest Path
* [ ] (Tour de algorithm) Self-balancing tree

**Comment by malkoG** [comment]
Reference https://codecatalog.org/articles/homebrew-download-strategy/
